import Head from "next/head";
import ProjectCard from "../components/project-card/ProjectCard";
import styles from "../styles/Home.module.scss";
import { Swiper, SwiperSlide } from "swiper/react";
import { Pagination, Grid } from "swiper";
import { useForm } from "react-hook-form";

// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/grid";

export default function Home() {
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm();
  const onSubmit = (data) => console.log(data);
  const projects = [
    {
      name: "REST API Countries Dashboard",
      description:
        "A country statistics dashboard created using React with data supplied by the restcountries.com api. Countries can be filtered by region and name.",
      image: "/rest-api-dashboard.png",
    },
    {
      name: "E-Commerce product page",
      description:
        "An exemplar page of an e-commerce website product created using React. The product can be added to the cart. Cart state is tracked using redux.",
      image: "/e-commerce-product-page.png",
    },
    {
      name: "Sunnyside agency landing page",
      description:
        "An exemplar landing page of a digital agency created using React.",
      image: "/sunnyside-agency-landing-page.png",
    },
    {
      name: "Teacozy Chatbot",
      description:
        "A full-stack application with React on the front-end and Express.js on the backend. It's a chatbot that allows customer of teashop to ask questions about their business.",
      image: "/tea-cozy-chatbot.png",
    },
  ];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.landing}>
        <div id="stars"></div>
        <div id="stars2"></div>
        <div id="stars3"></div>

        <section className={styles.landing_content}>
          <div className="flex items-center flex-wrap justify-center">
            <h1
              className={`font-bold text-xl md:text-2xl p-1 ${styles.landing_text}`}
            >
              Let's get your idea the moon!
            </h1>
            <div className={styles.welcome_image_container}>
              <img
                src="/assets/moon.png"
                alt=""
                className="absolute top-0 left-0 h-full w-full"
              />
              <img src="/assets/rocket.png" alt="" className={styles.rocket} />
            </div>
          </div>
          <button>Get in Touch</button>
        </section>
        <div className={styles.landing_links}>
          <img
            src="/assets/linkedin.png"
            alt=""
            className={`${styles.link} shadow-lg`}
          />
          <img
            src="/assets/twitter.png"
            alt=""
            className={`${styles.link} shadow-lg`}
          />
          <img
            src="/assets/github.jpeg"
            alt=""
            className={`${styles.link} shadow-lg`}
          />
        </div>
      </div>
      <div className="w-full flex flex-col justify-center items-center px-4 md:px-8">
        <section className={styles.about_me} id="aboutme">
          <h1 className={`font-bold text-3xl`}>About me</h1>
          <p style={{ lineHeight: "200%" }} className="mb-8">
            I am a full-stack developer who has a love for everything that is
            JavaScript my forte is combination of React on the front-end and
            Express.js/Node.js on the backend. I have dabbled in a range
            JavaScript frameworks such as Vue.js and Angular.
            <br />
            <br />I have been working as a full-stack developer for more than
            two years now and over that time I've worked with government clients
            and completed personal projects during which I had the opportunity
            to develop skills such as database management, quality analysis,
            application development and testing, I am always looking for more
            opportunities to challenge myself as a developer so please feel free
            to contact me.
          </p>
        </section>
        <div className={styles.skill_strip_container + " mb-6"}>
          {[...Array(2).keys()].map((el) => (
            <div className={styles.skill_strip} key={el}>
              <img
                src="/assets/react-logo.png"
                alt=""
                className={styles.skill}
              />
              <img
                src="/assets/html-logo.png"
                alt=""
                className={styles.skill}
              />
              <img
                src="/assets/nodejs-logo.png"
                alt=""
                className={styles.skill}
              />
              <img
                src="/assets/expressjs.png"
                alt=""
                className={styles.skill}
              />
              <img
                src="/assets/postgressql.png"
                alt=""
                className={styles.skill}
              />
              <img src="/assets/sql.png" alt="" className={styles.skill} />
              <img
                src="/assets/vuejs-logo.png"
                alt=""
                className={styles.skill}
              />
              <img src="/assets/css.png" alt="" className={styles.skill} />
              <img src="/assets/aws.png" alt="" className={styles.skill} />
            </div>
          ))}
        </div>

        <section
          className={styles.about_me + " mb-6 w-full max-w-screen-lg"}
          id="portfolio"
        >
          <h1 className={`font-bold text-3xl mb-6`}>Portfolio</h1>
          <Swiper
            modules={[Pagination, Grid]}
            spaceBetween={25}
            slidesPerView={1}
            grid={{
              rows: 1,
              fill: "row",
            }}
            breakpoints={{
              // when window width is >= 768px
              700: {
                slidesPerView: 2,
                spaceBetween: 25,
                grid: {
                  rows: 2,
                  fill: "row",
                },
              },
              // when window width is >= 900px
              1024: {
                slidesPerView: 3,
                spaceBetween: 25,
                grid: {
                  rows: 2,
                  fill: "row",
                },
              },
            }}
            pagination={{ clickable: true }}
            onSlideChange={() => console.log("slide change")}
            onSwiper={(swiper) => console.log(swiper)}
          >
            {projects.map((project) => (
              <SwiperSlide key={project.name}>
                <ProjectCard
                  {...{
                    image: project.image,
                    imageEndPoint: "/assets/project-images",
                    name: project.name,
                    description: project.description,
                  }}
                />
              </SwiperSlide>
            ))}
          </Swiper>
        </section>
        <section
          className={styles.contact_me + " mb-6 w-full max-w-screen-lg"}
          id="portfolio"
        >
          <h1 className={`font-bold text-3xl mb-6`}>Contact Me</h1>
          <form onSubmit={handleSubmit(onSubmit)}>
            <label htmlFor="firstName">First Name</label>
            <input type="text" {...register("firstName")} />
            <label htmlFor="lastName">Last Name</label>
            <input type="text" {...register("lastName")} />
            <label htmlFor="email">Email</label>
            <input type="text" {...register("email")} />
            <label htmlFor="query">Query</label>
            <input
              type="text"
              {...register("query")}
              id="query"
              style={{ height: "150px" }}
            />
            <button>Send</button>
          </form>
        </section>
      </div>
    </div>
  );
}
